### ISSUE TITLE
crash on recieve with FLEX

### ISSUE THREAD

**Issue by madmax-X** [lingfish/mmng-ui#3]
connect sdrpp to a local rtl_tcp server
network sink set to 127.0.0.1:8888

recieve pocsag/next transmisstion in sdrpp

crash mmng-ui

crash dump to follow:
```

$ mmng-ui 
╭───────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────╮
│ /home/[USERNAME]/.local/share/pipx/venvs/mmng-ui/lib/python3.12/site-packages/mmng_ui/pocsag.py:258 in on_output_message                                                                 │
│                                                                                                                                                                                      │
│   255 │   │   # Process the output as it becomes available                                     ╭────────────── locals ───────────────╮                                               │
│   256 │   │   log.write(f'[bold magenta]multimon-ng: {message.output}')                        │     log = RichLog(id='log')         │                                               │
│   257 │   │                                                                                    │ message = OutputMessage()           │                                               │
│ ❱ 258 │   │   result, json_detected = self.parse_line.parse(message.output)                    │    self = MainScreen()              │                                               │
│   259 │   │   self.log(f'result: {result}')                                                    │  status = StatusWidget(id='status') │                                               │
│   260 │   │                                                                                    │   table = DataTable(id='messages')  │                                               │
│   261 │   │   status.json_mode = json_detected                                                 ╰─────────────────────────────────────╯                                               │
│                                                                                                                                                                                      │
│ /home/[USERNAME]/.local/share/pipx/venvs/mmng-ui/lib/python3.12/site-packages/mmng_ui/reader.py:125 in parse                                                                             │
│                                                                                                                                                                                      │
│   122 │   │   │   elif re.search(r'FLEX[:|]', line):                                                                                                                                 │
│   123 │   │   │   │   address_match = re.search(r'FLEX[:|] ?.*?[\[|](\d*?)[\]| ]', line)                                                                                             │
│   124 │   │   │   │   if address_match:                                                                                                                                              │
│ ❱ 125 │   │   │   │   │   address = address_match.group(1).trim()                                                                                                                    │
│   126 │   │   │   │                                                                                                                                                                  │
│   127 │   │   │   │   # Handle timestamps within FLEX                                                                                                                                │
│   128 │   │   │   │   if self.use_timestamp:                                                                                                                                         │
│                                                                                                                                                                                      │
│ ╭────────────────────────────────────────────────────────── locals ──────────────────────────────────────────────────────────╮                                                       │
│ │ address_match = <re.Match object; span=(21, 75), match='FLEX|2024-12-08 15:11:24|3200/4/F/A|02.086|429496>                 │                                                       │
│ │     json_line = None                                                                                                       │                                                       │
│ │          line = '2024-12-08 10:11:24: FLEX|2024-12-08 15:11:24|3200/4/F/A|02.086|4294965699|ALN|*'+43                      │                                                       │
│ │       message = None                                                                                                       │                                                       │
│ │        result = PocsagMessage(current_time=<Moment(2024-12-08T10:11:24)>, timestamp=None, address=None, trim_message=None) │                                                       │
│ │          self = ParseLine(send_function_code=True, use_timestamp=True, json_detected=False)                                │                                                       │
│ │   time_string = None                                                                                                       │                                                       │
│ │     timestamp = None                                                                                                       │                                                       │
│ │  trim_message = None                                                                                                       │                                                       │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'str' object has no attribute 'trim'
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fefc1152700>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/lib/python3.12/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/lib/python3.12/asyncio/unix_events.py", line 767, in close
    self.write_eof()
  File "/usr/lib/python3.12/asyncio/unix_events.py", line 753, in write_eof
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_closed()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

```

**Comment by lingfish** [comment]
Thanks for this, looking into it now; the fix is obvious, but because I have no access to FLEX decode output from `multimon-ng`, I've had to do some guessing.

Could you run something similar (without `mmng-ui` in the middle), and paste here a few lines of the `multimon-ng` output for FLEX?

**Comment by lingfish** [comment]
This should be partially fixed by 77242a8ea0658def57cc63a1ddac84200379378c.

**Comment by lingfish** [comment]
No feedback, assume this is resolved.

**Comment by applecuckoo** [comment]
@lingfish just did a test with 1.4.0 and it still crashes - here's some samples of FLEX in JSON:

```json
{"timestamp":"2026-09-08 21:03:08","sync_baud":1600,"sync_level":2,"phase_number":"A","cycle_number":0,"frame_number":110,"capcode":1234567,"demod_name":"flex_alphanumeric","message":"This is a test periodic page. 59 09:03"}
{"timestamp":"2026-09-08 21:03:12","sync_baud":1600,"sync_level":2,"phase_number":"A","cycle_number":0,"frame_number":112,"capcode":1234567,"demod_name":"flex_alphanumeric","message":"This is a test periodic page. 59 09:03"}

{"timestamp":"2026-09-08 21:04:28","sync_baud":1600,"sync_level":2,"phase_number":"A","cycle_number":1,"frame_number":24,"capcode":997818,"demod_name":"flex_alphanumeric","message":"[redacted]"}
{"timestamp":"2026-09-08 21:04:28","sync_baud":1600,"sync_level":2,"phase_number":"A","cycle_number":1,"frame_number":24,"capcode":999075,"demod_name":"flex_alphanumeric","message":"[redacted]"}
{"timestamp":"2026-09-08 21:04:30","sync_baud":1600,"sync_level":2,"phase_number":"A","cycle_number":1,"frame_number":25,"capcode":999075,"demod_name":"flex_alphanumeric","message":"[redacted]"}
{"timestamp":"2026-09-08 21:04:30","sync_baud":1600,"sync_level":2,"phase_number":"A","cycle_number":1,"frame_number":25,"capcode":999135,"demod_name":"flex_alphanumeric","message":"[redacted]"}
{"timestamp":"2026-09-08 21:04:39","sync_baud":1600,"sync_level":2,"phase_number":"A","cycle_number":1,"frame_number":30,"capcode":997932,"demod_name":"flex_alphanumeric","message":"[redacted]"}
```

**Comment by lingfish** [comment]
Hi @applecuckoo do you have any error logs/exceptions for me?

**Comment by lingfish** [comment]
I'd still like any logs/exceptions, but I've pushed a new release that might fix it.

**Comment by applecuckoo** [comment]
> Hi [@applecuckoo](https://github.com/applecuckoo) do you have any error logs/exceptions for me?

sure, here's one:
```
╭─────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────────────────╮
│ /home/ac/pybox/lib/python3.13/site-packages/mmng_ui/pocsag.py:577 in on_output_message                                                                                                                   │
│                                                                                                                                                                                                          │
│   574 │   │   # Process the output as it becomes available                                     ╭───────────────────────────── locals ─────────────────────────────╮                                      │
│   575 │   │   log.write(f'[bold magenta]multimon-ng: {message.output}')                        │     log = RichLog(id='log-7355', classes='feed-log')             │                                      │
│   576 │   │                                                                                    │ message = OutputMessage()                                        │                                      │
│ ❱ 577 │   │   result, json_detected = self.parse_line.parse(message.output)                    │    self = FeedWidget()                                           │                                      │
│   578 │   │                                                                                    │  status = StatusWidget(id='status-7355', classes='feed-status')  │                                      │
│   579 │   │   status.json_mode = json_detected                                                 │   table = DataTable(id='messages-7355', classes='feed-messages') │                                      │
│   580                                                                                          ╰──────────────────────────────────────────────────────────────────╯                                      │
│                                                                                                                                                                                                          │
│ /home/ac/pybox/lib/python3.13/site-packages/mmng_ui/reader.py:65 in parse                                                                                                                                │
│                                                                                                                                                                                                          │
│    62 │   │   │   │   │   result.trim_message = f'ERROR: multimon-ng returned non-JSON: {line}                                                                                                           │
│    63 │   │   │   │   │   result.address = ''                                                                                                                                                            │
│    64 │   │   │   │   │   return result, self.json_detected                                                                                                                                              │
│ ❱  65 │   │   │   demod_name = json_line['demod_name']                                                                                                                                                   │
│    66 │   │   │   if 'pocsag' in demod_name.lower():                                                                                                                                                     │
│    67 │   │   │   │   result.trim_message = (                                                                                                                                                            │
│    68 │   │   │   │   │   re.sub(r'<[A-Za-z]{3}>', '', json_line.get('alpha', '')).replace('Ä'                                                                                                           │
│                                                                                                                                                                                                          │
│ ╭───────────────────────────────────────────────────────── locals ──────────────────────────────────────────────────────────╮                                                                            │
│ │    json_line = {                                                                                                          │                                                                            │
│ │                │   'timestamp': '2026-09-09 01:17:14',                                                                    │                                                                            │
│ │                │   'baud': 1600,                                                                                          │                                                                            │
│ │                │   'level': 2,                                                                                            │                                                                            │
│ │                │   'phase': 'A',                                                                                          │                                                                            │
│ │                │   'cycle': 4,                                                                                            │                                                                            │
│ │                │   'frame': 49,                                                                                           │                                                                            │
│ │                │   'capcode': 1234567,                                                                                    │                                                                            │
│ │                │   'addr_type': 'S',                                                                                      │                                                                            │
│ │                │   'is_group': False,                                                                                     │                                                                            │
│ │                │   'msg_type': 'alphanumeric',                                                                            │                                                                            │
│ │                │   ... +8                                                                                                 │                                                                            │
│ │                }                                                                                                          │                                                                            │
│ │         line = '{"timestamp":"2026-09-09 01:17:14","baud":1600,"level":2,"phase":"A","cycle":4,"'+245                     │                                                                            │
│ │      message = None                                                                                                       │                                                                            │
│ │       result = PocsagMessage(current_time=<Moment(2026-09-09T13:17:18)>, timestamp=None, address=None, trim_message=None) │                                                                            │
│ │         self = ParseLine(send_function_code=True, use_timestamp=True, json_detected=True)                                 │                                                                            │
│ │  time_string = None                                                                                                       │                                                                            │
│ │    timestamp = None                                                                                                       │                                                                            │
│ │ trim_message = None                                                                                                       │                                                                            │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'demod_name'
```

**Comment by applecuckoo** [comment]
yep, still hitting this error with 1.4.1

**Comment by applecuckoo** [comment]
@lingfish I suspect it might be because some packets (i.e. `{"baud":1600,"level":2,"phase":"A","cycle":5,"frame":119,"msg_type":"bch_stats","polarity":"POS","bch_0err":88,"bch_1err":0,"bch_2err":0,"bch_uncorr":0,"errbits":0}`) don't specifically have a mode attached

**Comment by lingfish** [comment]
Ok, I've dug deeper. Looks like the `multimon-ng` author pushed 1.6.0 (which you're also using), and this brings with it changes to the JSON output.

### Legacy FLEX (demod_flex.c)
```json
{"demod_name":"flex_alphanumeric", "capcode":1234567, "sync_baud":1600, ...}
```

### FLEX_NEXT (demod_flex_next.c) — no demod_name field
```json
{"msg_type":"alphanumeric", "capcode":1234567, "baud":1600, ...}
```

FLEX_NEXT also emits non-message packets like `bch_stats`, `biw_sysid`, `biw_date`, etc. — all without `demod_name`.

### The reader.py problem (line 65)
```python
demod_name = json_line['demod_name']  # KeyError on FLEX_NEXT output
```

This is a hard crash on any FLEX_NEXT packet.

Here's the timeline:

### multimon-ng release history (relevant)

| Version | Date | Key change |
|---------|------|------------|
| **1.2.0** | Oct 19, 2022 | FLEX and FLEX_NEXT **separated** — FLEX reverted to legacy, FLEX_NEXT became its own demod |
| **1.4.0** | Feb 19, 2026 | JSON output added (by @lingfish ) — only for legacy FLEX (`demod_name`) and POCSAG |
| **1.6.0** | Jul 27, 2026 | **Major FLEX_NEXT rewrite** by @VasylSamoilov in https://github.com/EliasOenal/multimon-ng/pull/262 - new JSON format with `msg_type` instead of `demod_name`, plus `bch_stats`, `biw_*` packets |

### The crash source

The reporter (`applecuckoo`) is running **multimon-ng 1.6.0**, which outputs the new FLEX_NEXT JSON schema:

```json
{"msg_type":"alphanumeric", "capcode":1234567, "baud":1600, ...}
```

Our existing test data is all **multimon-ng 1.4.0** legacy FLEX format:

```json
{"demod_name":"flex_alphanumeric", "capcode":4294962309, "sync_baud":1600, ...}
```

The FLEX_NEXT JSON with `msg_type` only exists since **1.6.0** (July 2026).

**Comment by lingfish** [comment]
Hi again @applecuckoo - are you fluent enough to be able to `pipx` install a GitHub branch, and could test this branch: https://github.com/lingfish/mmng-ui/tree/fix/flex-next-json-support

**Comment by VasylSamoilov** [comment]
There is intention to make common and consistent delimited output ( https://github.com/EliasOenal/multimon-ng/issues/255#issuecomment-4721617320 ) and this should also apply to json output, but we are not there yet. Any ideas how to make it better would be appreciated.

**Comment by lingfish** [comment]
> There is intention to make common and consistent delimited output ( [EliasOenal/multimon-ng#255 (comment)](https://github.com/EliasOenal/multimon-ng/issues/255#issuecomment-4721617320) ) and this should also apply to json output, but we are not there yet. Any ideas how to make it better would be appreciated.

Sure, I have some ideas (I'm the contributor that first put any JSON in, with the desire to extend and standardise it).

The key thing to fix is that your commits broke third party stuff like mine 😉  I'll leave some thoughts over on the above referenced issue.

**Comment by VasylSamoilov** [comment]
FLEX is quite complex and tightly packed protocol, not a simple capcode+message output. It's not trivial to map all possible useful information to proper outputs. And on top of that, POCSAG and FLEX has character encodings for different regions that I even didn't begin to implement in multimon-ng, as it probably not the right place to put it, it affects message display, not protocol decoding. Would appreciate some ideas on that also.

**Comment by applecuckoo** [comment]
> Hi again [@applecuckoo](https://github.com/applecuckoo) - are you fluent enough to be able to `pipx` install a GitHub branch, and could test this branch: https://github.com/lingfish/mmng-ui/tree/fix/flex-next-json-support

@lingfish can confirm this works

**Comment by lingfish** [comment]
Cool, merging now. Thanks for this!

**Comment by lingfish** [comment]
Pushing 1.4.2 now, should be all good in about 10 minutes.
